language: java
install: true
addons:
    sonarcloud:
      organization: "uklimaschewski"
      token:
        secure: "5add0ba264fa6733c4acdb84c5af69096f0c69ae"
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Dsonar.projectKey=uklimaschewski_EvalEx
cache:
  directories:
    - $HOME/.m2
